### model
#model_name_or_path: /data1/models/OS-Atlas-Pro-7B
model_name_or_path: /data1/models/Qwen2-VL-7B-Instruct
#/data1/models/Qwen2-VL-7B-Instruct
### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /data3/wuzh/LLaMA-Factory-main/examples/deepspeed/ds_z3_config.json

### dataset
dataset: AITZ_OOD
template: qwen2_vl
cutoff_len: 4096
max_samples: 9999999
#max_samples: 999
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data3/wuzh/OOD/weight/AITZ
logging_steps: 10
save_steps: 60000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 7.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 20000
